#define PACMAN_DB_PATH "/home/madhatter/pacman"
#define ETHERNET_DEVICE "enp0s25"
#define ETHERNET_STRING "connected"
#define WIRELESS_DEVICE "wlp12s0"
#define OFFLINE_STRING "offline"
#define BATTERY_NOW "/sys/class/power_supply/BAT0/charge_now"
#define BATTERY_FULL "/sys/class/power_supply/BAT0/charge_full"
#define ENABLE_BATTERY 1
#define ENABLE_WIRELESS 1
#define ENABLE_DROPBOX 1
